;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack",DevComment="Attack")
+GameplayTagList=(Tag="Ability.Attack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Attack",DevComment="")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Release",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Hit",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Tier.One.John",DevComment="")
+GameplayTagList=(Tag="Tier.Three.John",DevComment="")
+GameplayTagList=(Tag="Tier.Two.John",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Ariel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Bakin",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Biden",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.CaptainMel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Cow",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Daiye",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Elizabeth",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Gallagher",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.GoblinJohn",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Heart",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Howl",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Isabel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Joe",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.John",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Kaya",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Kisha",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mac",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Melanie",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mock",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Rose",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Sarah",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Smith",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Sylph",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Tah",DevComment="")
+GameplayTagList=(Tag="Unit.Minion.Wraith",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.John",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.John",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.John",DevComment="")

