;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Isabel",NewTagName="Unit.Tier2.Isabel")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Biden",NewTagName="Unit.Tier2.Biden")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Kaya",NewTagName="Unit.Tier2.Kaya")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.GoblinJohn",NewTagName="Unit.Tier2.GoblinJohn")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Tah",NewTagName="Unit.Tier2.Tah")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Mel",NewTagName="Unit.Tier2.Mel")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Mac",NewTagName="Unit.Tier2.Mac")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Mock",NewTagName="Unit.Tier2.Mock")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Bakin",NewTagName="Unit.Tier2.Bakin")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Ariel",NewTagName="Unit.Tier2.Ariel")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Kisha",NewTagName="Unit.Tier2.Kisha")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Elizabeth",NewTagName="Unit.Tier2.Elizabeth")
+GameplayTagRedirects=(OldTagName="Unit.Tier1.Smith",NewTagName="Unit.Tier2.Smith")
+GameplayTagRedirects=(OldTagName="Unit.Tier2.Ariel",NewTagName="Unit.Tier3.Ariel")
+GameplayTagRedirects=(OldTagName="Unit.Tier2.Kisha",NewTagName="Unit.Tier3.Kisha")
+GameplayTagRedirects=(OldTagName="Unit.Tier2.Elizabeth",NewTagName="Unit.Tier3.Elizabeth")
+GameplayTagRedirects=(OldTagName="Unit.Tier2.Smith",NewTagName="Unit.Tier3.Smith")
+GameplayTagList=(Tag="Ability.Attack",DevComment="Attack")
+GameplayTagList=(Tag="Ability.Attack.Cooldown",DevComment="")
+GameplayTagList=(Tag="Attack",DevComment="")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Release",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Hit",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Tier.One.John",DevComment="")
+GameplayTagList=(Tag="Tier.Three.John",DevComment="")
+GameplayTagList=(Tag="Tier.Two.John",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Ariel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Bakin",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Biden",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.CaptainMel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Cow",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Daiye",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Elizabeth",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Gallagher",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.GoblinJohn",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Heart",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Howl",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Isabel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Joe",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.John",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Kaya",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Kisha",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mac",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mel",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Melanie",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Mock",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Rose",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Sarah",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Smith",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Sylph",DevComment="")
+GameplayTagList=(Tag="Unit.Hero.Tah",DevComment="")
+GameplayTagList=(Tag="Unit.Minion.Wraith",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Cow",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Daiye",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Gallagher",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Heart",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Howl",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Joe",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.John",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Melanie",DevComment="")
+GameplayTagList=(Tag="Unit.Tier1.Sarah",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Bakin",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Biden",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.GoblinJohn",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Isabel",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.John",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Kaya",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Mac",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Mel",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Mock",DevComment="")
+GameplayTagList=(Tag="Unit.Tier2.Tah",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Ariel",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.CaptainMel",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Elizabeth",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.John",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Kisha",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Rose",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Smith",DevComment="")
+GameplayTagList=(Tag="Unit.Tier3.Sylph",DevComment="")
+GameplayTagList=(Tag="Zone.Area.A",DevComment="")

