// Copyright (c) 2025 TeamNG. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace NGGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Town_Elf);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Town_Dwarf);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Town_Human);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Event_Default);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Event_Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Event_Hidden);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_General);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Shop);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Event);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Rest);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Elite);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Node_Named);
	
	// 마을 버프 태그
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TownBuff_ExtraGold);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TownBuff_AttackBoost);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TownBuff_DefenseBoost);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TownBuff_StartUnit);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Melee);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Release);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_JobSkill_John);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_BaseDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_ADMultiplier);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_APMultiplier);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_SkillMultiplier);
}